
package PGA_Interfaz;

/**
 *
 * @author Dario
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelTabs = new javax.swing.JTabbedPane();
        alumnosTab = new javax.swing.JPanel();
        alumnosScroll = new javax.swing.JScrollPane();
        alumnosTabla = new javax.swing.JTable();
        alumnoDatosPanel = new javax.swing.JPanel();
        alumnoNombreText = new javax.swing.JTextField();
        alumnoDomicilioText = new javax.swing.JTextField();
        alumnoLegajoLabel = new javax.swing.JLabel();
        alumnoNombreLabel = new javax.swing.JLabel();
        alumnoDomicilioLabel = new javax.swing.JLabel();
        alumnoAsigScroll = new javax.swing.JScrollPane();
        alumnoAsigTabla = new javax.swing.JTable();
        alumnoAsigLabel = new javax.swing.JLabel();
        alumnoMailLabel = new javax.swing.JLabel();
        alumnoMailText = new javax.swing.JTextField();
        alumnoAsigBotonesPanel = new javax.swing.JPanel();
        alumnoAgregarAsigBoton = new javax.swing.JButton();
        alumnoQuitarAsigBoton = new javax.swing.JButton();
        alumnoLegajoText = new javax.swing.JFormattedTextField();
        alumnosBotonesPanel = new javax.swing.JPanel();
        alumnosNuevoBoton = new javax.swing.JButton();
        alumnosBorrarBoton = new javax.swing.JButton();
        alumnoBotonesPanel = new javax.swing.JPanel();
        alumnoEditarBoton = new javax.swing.JButton();
        alumnoCancelarBoton = new javax.swing.JButton();
        alumnoAceptarBoton = new javax.swing.JButton();
        alumnosFiltro = new javax.swing.JTextField();
        profesoresTab = new javax.swing.JPanel();
        profesoresScroll = new javax.swing.JScrollPane();
        profesoresTabla = new javax.swing.JTable();
        profesoresBotonesPanel = new javax.swing.JPanel();
        profesoresNuevoBoton = new javax.swing.JButton();
        profesoresBorrarBoton = new javax.swing.JButton();
        profesorBotonesPanel = new javax.swing.JPanel();
        profesorEditarBoton = new javax.swing.JButton();
        profesorCancelarBoton = new javax.swing.JButton();
        profesorAceptarBoton = new javax.swing.JButton();
        profesoresFiltro = new javax.swing.JTextField();
        profesorDatosPanel = new javax.swing.JPanel();
        profesorNombreText = new javax.swing.JTextField();
        profesorDomicilioText = new javax.swing.JTextField();
        profesorLegajoLabel = new javax.swing.JLabel();
        profesorNombreLabel = new javax.swing.JLabel();
        profesorDomicilioLabel = new javax.swing.JLabel();
        profesorAsigScroll = new javax.swing.JScrollPane();
        profesorAsigTabla = new javax.swing.JTable();
        profesorAsigLabel = new javax.swing.JLabel();
        profesorMailLabel = new javax.swing.JLabel();
        profesorMailText = new javax.swing.JTextField();
        profesorAsigBotonesPanel = new javax.swing.JPanel();
        profesorAgregarAsigBoton = new javax.swing.JButton();
        profesorQuitarAsigBoton = new javax.swing.JButton();
        profesorLegajoText = new javax.swing.JFormattedTextField();
        asignaturasTab = new javax.swing.JPanel();
        asignaturasScroll = new javax.swing.JScrollPane();
        asignaturasTabla = new javax.swing.JTable();
        asignaturaDatosPanel = new javax.swing.JPanel();
        asignaturaCorrLabel = new javax.swing.JLabel();
        asignaturaCorrScroll = new javax.swing.JScrollPane();
        asignaturaCorrTabla = new javax.swing.JTable();
        asignaturaCorrBotonesPanel = new javax.swing.JPanel();
        asignaturaCorrAgregarBoton = new javax.swing.JButton();
        asignaturaCorrQuitarBoton = new javax.swing.JButton();
        asignaturaIdLabel = new javax.swing.JLabel();
        asignaturaNombreText = new javax.swing.JTextField();
        asignaturaNombreLabel = new javax.swing.JLabel();
        asignaturaIdText = new javax.swing.JFormattedTextField();
        asignaturasBotonesPanel = new javax.swing.JPanel();
        asignaturasNuevoBoton = new javax.swing.JButton();
        asignaturasBorrarBoton = new javax.swing.JButton();
        asignaturaBotonesPanel = new javax.swing.JPanel();
        asignaturaEditarBoton = new javax.swing.JButton();
        asignaturaCancelarBoton = new javax.swing.JButton();
        asignaturaAceptarBoton = new javax.swing.JButton();
        asignaturasFiltro = new javax.swing.JTextField();
        cursadasTab = new javax.swing.JPanel();
        cursadasScroll = new javax.swing.JScrollPane();
        cursadasTabla = new javax.swing.JTable();
        cursadaDatosPanel = new javax.swing.JPanel();
        cursadaIdLabel = new javax.swing.JLabel();
        cursadaNombreLabel = new javax.swing.JLabel();
        cursadaNombreText = new javax.swing.JTextField();
        cursadaPeriodoLabel = new javax.swing.JLabel();
        cursadaDiaCombo = new javax.swing.JComboBox<>();
        cursadaPeriodoACombo = new javax.swing.JComboBox<>();
        cursadaPeriodoBText = new javax.swing.JFormattedTextField();
        cursadaHoraInicioText = new javax.swing.JFormattedTextField();
        cursadaHoraFinText = new javax.swing.JFormattedTextField();
        cursadaHoraLabel = new javax.swing.JLabel();
        cursadaAlumLabel = new javax.swing.JLabel();
        cursadaAlumScroll = new javax.swing.JScrollPane();
        cursadaAlumTabla = new javax.swing.JTable();
        cursadaAlumBotonesPanel = new javax.swing.JPanel();
        cursadaAlumAgregarBoton = new javax.swing.JButton();
        cursadaAlumQuitarBoton = new javax.swing.JButton();
        cursadaProfBotonesPanel = new javax.swing.JPanel();
        cursadaProfAgregarBoton = new javax.swing.JButton();
        cursadaProfQuitarBoton = new javax.swing.JButton();
        cursadaProfScroll = new javax.swing.JScrollPane();
        cursadaProfTabla = new javax.swing.JTable();
        cursadaProfLabel = new javax.swing.JLabel();
        cursadaIdText = new javax.swing.JFormattedTextField();
        cursadasBotonesPanel = new javax.swing.JPanel();
        cursadasNuevoBoton = new javax.swing.JButton();
        cursadasBorrarBoton = new javax.swing.JButton();
        cursadaBotonesPanel = new javax.swing.JPanel();
        cursadaEditarBoton = new javax.swing.JButton();
        cursadaCancelarBoton = new javax.swing.JButton();
        cursadaAceptarBoton = new javax.swing.JButton();
        cursadasFiltro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelTabs.setToolTipText("");

        alumnosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alumnosTabla.setColumnSelectionAllowed(true);
        alumnosTabla.getTableHeader().setReorderingAllowed(false);
        alumnosScroll.setViewportView(alumnosTabla);
        alumnosTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (alumnosTabla.getColumnModel().getColumnCount() > 0) {
            alumnosTabla.getColumnModel().getColumn(0).setResizable(false);
            alumnosTabla.getColumnModel().getColumn(0).setHeaderValue("Legajo");
            alumnosTabla.getColumnModel().getColumn(1).setResizable(false);
            alumnosTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        alumnoDatosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        alumnoNombreText.setText("Nombre de alumno");
        alumnoNombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoNombreTextActionPerformed(evt);
            }
        });

        alumnoDomicilioText.setText("Domicilio de alumno");

        alumnoLegajoLabel.setText("Legajo");

        alumnoNombreLabel.setText("Nombre");

        alumnoDomicilioLabel.setText("Domicilio");

        alumnoAsigTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alumnoAsigTabla.getTableHeader().setReorderingAllowed(false);
        alumnoAsigScroll.setViewportView(alumnoAsigTabla);
        alumnoAsigTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (alumnoAsigTabla.getColumnModel().getColumnCount() > 0) {
            alumnoAsigTabla.getColumnModel().getColumn(0).setResizable(false);
            alumnoAsigTabla.getColumnModel().getColumn(0).setHeaderValue("Legajo");
            alumnoAsigTabla.getColumnModel().getColumn(1).setResizable(false);
            alumnoAsigTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        alumnoAsigLabel.setText("Asignaturas aprobadas");

        alumnoMailLabel.setText("Mail");

        alumnoMailText.setText("Mail de alumno");

        alumnoAgregarAsigBoton.setText("Agregar...");
        alumnoAgregarAsigBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoAgregarAsigBotonActionPerformed(evt);
            }
        });

        alumnoQuitarAsigBoton.setText("Quitar");
        alumnoQuitarAsigBoton.setEnabled(false);
        alumnoQuitarAsigBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoQuitarAsigBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alumnoAsigBotonesPanelLayout = new javax.swing.GroupLayout(alumnoAsigBotonesPanel);
        alumnoAsigBotonesPanel.setLayout(alumnoAsigBotonesPanelLayout);
        alumnoAsigBotonesPanelLayout.setHorizontalGroup(
            alumnoAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alumnoAsigBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alumnoAgregarAsigBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnoQuitarAsigBoton)
                .addGap(0, 0, 0))
        );
        alumnoAsigBotonesPanelLayout.setVerticalGroup(
            alumnoAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alumnoAsigBotonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(alumnoAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoAgregarAsigBoton)
                    .addComponent(alumnoQuitarAsigBoton)))
        );

        try {
            alumnoLegajoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("'A'L'U####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        alumnoLegajoText.setText("ALU0000");
        alumnoLegajoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoLegajoTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alumnoDatosPanelLayout = new javax.swing.GroupLayout(alumnoDatosPanel);
        alumnoDatosPanel.setLayout(alumnoDatosPanelLayout);
        alumnoDatosPanelLayout.setHorizontalGroup(
            alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnoAsigScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addGroup(alumnoDatosPanelLayout.createSequentialGroup()
                        .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(alumnoMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alumnoDomicilioLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alumnoNombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alumnoLegajoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alumnoNombreText)
                            .addComponent(alumnoDomicilioText)
                            .addComponent(alumnoMailText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alumnoLegajoText, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(alumnoDatosPanelLayout.createSequentialGroup()
                        .addComponent(alumnoAsigLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(alumnoAsigBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        alumnoDatosPanelLayout.setVerticalGroup(
            alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoLegajoLabel)
                    .addComponent(alumnoLegajoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alumnoNombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoDomicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alumnoDomicilioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alumnoDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alumnoMailLabel))
                .addGap(28, 28, 28)
                .addComponent(alumnoAsigLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnoAsigScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnoAsigBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        alumnosNuevoBoton.setText("Nuevo");

        alumnosBorrarBoton.setText("Borrar");
        alumnosBorrarBoton.setEnabled(false);

        javax.swing.GroupLayout alumnosBotonesPanelLayout = new javax.swing.GroupLayout(alumnosBotonesPanel);
        alumnosBotonesPanel.setLayout(alumnosBotonesPanelLayout);
        alumnosBotonesPanelLayout.setHorizontalGroup(
            alumnosBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnosBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alumnosNuevoBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnosBorrarBoton)
                .addGap(0, 0, 0))
        );
        alumnosBotonesPanelLayout.setVerticalGroup(
            alumnosBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnosBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(alumnosBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnosNuevoBoton)
                    .addComponent(alumnosBorrarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alumnoEditarBoton.setText("Editar");
        alumnoEditarBoton.setEnabled(false);

        alumnoCancelarBoton.setText("Cancelar");
        alumnoCancelarBoton.setEnabled(false);

        alumnoAceptarBoton.setText("Aceptar");
        alumnoAceptarBoton.setEnabled(false);

        javax.swing.GroupLayout alumnoBotonesPanelLayout = new javax.swing.GroupLayout(alumnoBotonesPanel);
        alumnoBotonesPanel.setLayout(alumnoBotonesPanelLayout);
        alumnoBotonesPanelLayout.setHorizontalGroup(
            alumnoBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alumnoEditarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnoAceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnoCancelarBoton)
                .addGap(0, 0, 0))
        );
        alumnoBotonesPanelLayout.setVerticalGroup(
            alumnoBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(alumnoBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoEditarBoton)
                    .addComponent(alumnoCancelarBoton)
                    .addComponent(alumnoAceptarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alumnosFiltro.setToolTipText("Filtrar el listado");

        javax.swing.GroupLayout alumnosTabLayout = new javax.swing.GroupLayout(alumnosTab);
        alumnosTab.setLayout(alumnosTabLayout);
        alumnosTabLayout.setHorizontalGroup(
            alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnosBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alumnosScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(alumnosFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alumnoBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alumnoDatosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        alumnosTabLayout.setVerticalGroup(
            alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnoDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(alumnosTabLayout.createSequentialGroup()
                        .addComponent(alumnosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alumnosScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alumnosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnoBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alumnosBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelTabs.addTab("Alumnos", alumnosTab);

        profesoresTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        profesoresTabla.getTableHeader().setReorderingAllowed(false);
        profesoresScroll.setViewportView(profesoresTabla);
        profesoresTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (profesoresTabla.getColumnModel().getColumnCount() > 0) {
            profesoresTabla.getColumnModel().getColumn(0).setResizable(false);
            profesoresTabla.getColumnModel().getColumn(0).setHeaderValue("Legajo");
            profesoresTabla.getColumnModel().getColumn(1).setResizable(false);
            profesoresTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        profesoresNuevoBoton.setText("Nuevo");

        profesoresBorrarBoton.setText("Borrar");
        profesoresBorrarBoton.setEnabled(false);

        javax.swing.GroupLayout profesoresBotonesPanelLayout = new javax.swing.GroupLayout(profesoresBotonesPanel);
        profesoresBotonesPanel.setLayout(profesoresBotonesPanelLayout);
        profesoresBotonesPanelLayout.setHorizontalGroup(
            profesoresBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profesoresNuevoBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesoresBorrarBoton)
                .addGap(0, 0, 0))
        );
        profesoresBotonesPanelLayout.setVerticalGroup(
            profesoresBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(profesoresBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesoresNuevoBoton)
                    .addComponent(profesoresBorrarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profesorEditarBoton.setText("Editar");
        profesorEditarBoton.setEnabled(false);

        profesorCancelarBoton.setText("Cancelar");
        profesorCancelarBoton.setEnabled(false);

        profesorAceptarBoton.setText("Aceptar");
        profesorAceptarBoton.setEnabled(false);

        javax.swing.GroupLayout profesorBotonesPanelLayout = new javax.swing.GroupLayout(profesorBotonesPanel);
        profesorBotonesPanel.setLayout(profesorBotonesPanelLayout);
        profesorBotonesPanelLayout.setHorizontalGroup(
            profesorBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesorBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profesorEditarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesorAceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesorCancelarBoton)
                .addGap(0, 0, 0))
        );
        profesorBotonesPanelLayout.setVerticalGroup(
            profesorBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesorBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(profesorBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorEditarBoton)
                    .addComponent(profesorCancelarBoton)
                    .addComponent(profesorAceptarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profesoresFiltro.setToolTipText("Filtrar el listado");

        profesorDatosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        profesorNombreText.setText("Nombre de profesor");

        profesorDomicilioText.setText("Domicilio de profesor");

        profesorLegajoLabel.setText("Legajo");

        profesorNombreLabel.setText("Nombre");

        profesorDomicilioLabel.setText("Domicilio");

        profesorAsigTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        profesorAsigTabla.getTableHeader().setReorderingAllowed(false);
        profesorAsigScroll.setViewportView(profesorAsigTabla);
        profesorAsigTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (profesorAsigTabla.getColumnModel().getColumnCount() > 0) {
            profesorAsigTabla.getColumnModel().getColumn(0).setResizable(false);
            profesorAsigTabla.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            profesorAsigTabla.getColumnModel().getColumn(1).setResizable(false);
            profesorAsigTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        profesorAsigLabel.setText("Asignaturas habilitadas");

        profesorMailLabel.setText("Mail");

        profesorMailText.setText("Mail de profesor");

        profesorAgregarAsigBoton.setText("Agregar...");
        profesorAgregarAsigBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorAgregarAsigBotonActionPerformed(evt);
            }
        });

        profesorQuitarAsigBoton.setText("Quitar");
        profesorQuitarAsigBoton.setEnabled(false);
        profesorQuitarAsigBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorQuitarAsigBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profesorAsigBotonesPanelLayout = new javax.swing.GroupLayout(profesorAsigBotonesPanel);
        profesorAsigBotonesPanel.setLayout(profesorAsigBotonesPanelLayout);
        profesorAsigBotonesPanelLayout.setHorizontalGroup(
            profesorAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profesorAsigBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profesorAgregarAsigBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesorQuitarAsigBoton)
                .addGap(0, 0, 0))
        );
        profesorAsigBotonesPanelLayout.setVerticalGroup(
            profesorAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profesorAsigBotonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(profesorAsigBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorAgregarAsigBoton)
                    .addComponent(profesorQuitarAsigBoton)))
        );

        try {
            profesorLegajoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("'P'R'O####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        profesorLegajoText.setText("PRO0000");

        javax.swing.GroupLayout profesorDatosPanelLayout = new javax.swing.GroupLayout(profesorDatosPanel);
        profesorDatosPanel.setLayout(profesorDatosPanelLayout);
        profesorDatosPanelLayout.setHorizontalGroup(
            profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesorDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesorAsigScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(profesorDatosPanelLayout.createSequentialGroup()
                        .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(profesorMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profesorDomicilioLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profesorNombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profesorLegajoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profesorMailText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profesorDomicilioText)
                            .addComponent(profesorNombreText)
                            .addComponent(profesorLegajoText, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(profesorDatosPanelLayout.createSequentialGroup()
                        .addComponent(profesorAsigLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profesorAsigBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        profesorDatosPanelLayout.setVerticalGroup(
            profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesorDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorLegajoLabel)
                    .addComponent(profesorLegajoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesorNombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorDomicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesorDomicilioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profesorDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesorMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesorMailLabel))
                .addGap(28, 28, 28)
                .addComponent(profesorAsigLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesorAsigScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesorAsigBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout profesoresTabLayout = new javax.swing.GroupLayout(profesoresTab);
        profesoresTab.setLayout(profesoresTabLayout);
        profesoresTabLayout.setHorizontalGroup(
            profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profesoresBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profesoresScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(profesoresFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profesorBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profesorDatosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        profesoresTabLayout.setVerticalGroup(
            profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profesoresTabLayout.createSequentialGroup()
                        .addComponent(profesoresFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profesoresScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(profesorDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profesoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesorBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesoresBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelTabs.addTab("Profesores", profesoresTab);

        asignaturasTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        asignaturasTabla.getTableHeader().setReorderingAllowed(false);
        asignaturasScroll.setViewportView(asignaturasTabla);
        asignaturasTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (asignaturasTabla.getColumnModel().getColumnCount() > 0) {
            asignaturasTabla.getColumnModel().getColumn(0).setResizable(false);
            asignaturasTabla.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            asignaturasTabla.getColumnModel().getColumn(1).setResizable(false);
            asignaturasTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        asignaturaDatosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        asignaturaCorrLabel.setText("Correlativas");

        asignaturaCorrTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        asignaturaCorrTabla.getTableHeader().setReorderingAllowed(false);
        asignaturaCorrScroll.setViewportView(asignaturaCorrTabla);
        asignaturaCorrTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (asignaturaCorrTabla.getColumnModel().getColumnCount() > 0) {
            asignaturaCorrTabla.getColumnModel().getColumn(0).setResizable(false);
            asignaturaCorrTabla.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            asignaturaCorrTabla.getColumnModel().getColumn(1).setResizable(false);
            asignaturaCorrTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        asignaturaCorrAgregarBoton.setText("Agregar...");
        asignaturaCorrAgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignaturaCorrAgregarBotonActionPerformed(evt);
            }
        });

        asignaturaCorrQuitarBoton.setText("Quitar");
        asignaturaCorrQuitarBoton.setEnabled(false);
        asignaturaCorrQuitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignaturaCorrQuitarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asignaturaCorrBotonesPanelLayout = new javax.swing.GroupLayout(asignaturaCorrBotonesPanel);
        asignaturaCorrBotonesPanel.setLayout(asignaturaCorrBotonesPanelLayout);
        asignaturaCorrBotonesPanelLayout.setHorizontalGroup(
            asignaturaCorrBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignaturaCorrBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignaturaCorrAgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturaCorrQuitarBoton)
                .addGap(0, 0, 0))
        );
        asignaturaCorrBotonesPanelLayout.setVerticalGroup(
            asignaturaCorrBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignaturaCorrBotonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(asignaturaCorrBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaCorrAgregarBoton)
                    .addComponent(asignaturaCorrQuitarBoton)))
        );

        asignaturaIdLabel.setText("ID");

        asignaturaNombreText.setText("jTextField2");

        asignaturaNombreLabel.setText("Nombre");

        try {
            asignaturaIdText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("'A'S'I####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout asignaturaDatosPanelLayout = new javax.swing.GroupLayout(asignaturaDatosPanel);
        asignaturaDatosPanel.setLayout(asignaturaDatosPanelLayout);
        asignaturaDatosPanelLayout.setHorizontalGroup(
            asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturaDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignaturaCorrScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addComponent(asignaturaCorrBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(asignaturaDatosPanelLayout.createSequentialGroup()
                        .addComponent(asignaturaCorrLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignaturaDatosPanelLayout.createSequentialGroup()
                        .addGroup(asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(asignaturaNombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asignaturaIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asignaturaNombreText)
                            .addComponent(asignaturaIdText))))
                .addContainerGap())
        );
        asignaturaDatosPanelLayout.setVerticalGroup(
            asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignaturaDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaIdLabel)
                    .addComponent(asignaturaIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asignaturaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignaturaNombreLabel))
                .addGap(18, 18, 18)
                .addComponent(asignaturaCorrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturaCorrScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturaCorrBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        asignaturasNuevoBoton.setText("Nuevo");

        asignaturasBorrarBoton.setText("Borrar");
        asignaturasBorrarBoton.setEnabled(false);

        javax.swing.GroupLayout asignaturasBotonesPanelLayout = new javax.swing.GroupLayout(asignaturasBotonesPanel);
        asignaturasBotonesPanel.setLayout(asignaturasBotonesPanelLayout);
        asignaturasBotonesPanelLayout.setHorizontalGroup(
            asignaturasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturasBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignaturasNuevoBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturasBorrarBoton)
                .addGap(0, 0, 0))
        );
        asignaturasBotonesPanelLayout.setVerticalGroup(
            asignaturasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturasBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(asignaturasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturasNuevoBoton)
                    .addComponent(asignaturasBorrarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        asignaturaEditarBoton.setText("Editar");
        asignaturaEditarBoton.setEnabled(false);

        asignaturaCancelarBoton.setText("Cancelar");
        asignaturaCancelarBoton.setEnabled(false);

        asignaturaAceptarBoton.setText("Aceptar");
        asignaturaAceptarBoton.setEnabled(false);

        javax.swing.GroupLayout asignaturaBotonesPanelLayout = new javax.swing.GroupLayout(asignaturaBotonesPanel);
        asignaturaBotonesPanel.setLayout(asignaturaBotonesPanelLayout);
        asignaturaBotonesPanelLayout.setHorizontalGroup(
            asignaturaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturaBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignaturaEditarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturaAceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignaturaCancelarBoton)
                .addGap(0, 0, 0))
        );
        asignaturaBotonesPanelLayout.setVerticalGroup(
            asignaturaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturaBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(asignaturaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaEditarBoton)
                    .addComponent(asignaturaCancelarBoton)
                    .addComponent(asignaturaAceptarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        asignaturasFiltro.setToolTipText("Filtrar el listado");

        javax.swing.GroupLayout asignaturasTabLayout = new javax.swing.GroupLayout(asignaturasTab);
        asignaturasTab.setLayout(asignaturasTabLayout);
        asignaturasTabLayout.setHorizontalGroup(
            asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(asignaturasBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(asignaturasScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(asignaturasFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignaturaBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignaturasTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(asignaturaDatosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        asignaturasTabLayout.setVerticalGroup(
            asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignaturasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignaturaDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(asignaturasTabLayout.createSequentialGroup()
                        .addComponent(asignaturasFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asignaturasScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asignaturasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignaturaBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignaturasBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelTabs.addTab("Asignaturas", asignaturasTab);

        cursadasTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursadasTabla.getTableHeader().setReorderingAllowed(false);
        cursadasScroll.setViewportView(cursadasTabla);
        cursadasTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (cursadasTabla.getColumnModel().getColumnCount() > 0) {
            cursadasTabla.getColumnModel().getColumn(0).setResizable(false);
            cursadasTabla.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            cursadasTabla.getColumnModel().getColumn(1).setResizable(false);
            cursadasTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        cursadaDatosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        cursadaIdLabel.setText("ID");

        cursadaNombreLabel.setText("Nombre");

        cursadaNombreText.setText("jTextField2");

        cursadaPeriodoLabel.setText("Periodo");

        cursadaDiaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lun", "Mar", "Mié", "Jue", "Vie", "Sab", "Dom" }));

        cursadaPeriodoACombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02" }));
        cursadaPeriodoACombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaPeriodoAComboActionPerformed(evt);
            }
        });

        try {
            cursadaPeriodoBText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cursadaPeriodoBText.setText("2017");

        try {
            cursadaHoraInicioText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cursadaHoraInicioText.setText("14:00");
        cursadaHoraInicioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaHoraInicioTextActionPerformed(evt);
            }
        });

        try {
            cursadaHoraFinText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cursadaHoraFinText.setText("14:00");
        cursadaHoraFinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaHoraFinTextActionPerformed(evt);
            }
        });

        cursadaHoraLabel.setText("a");

        cursadaAlumLabel.setText("Alumnos");

        cursadaAlumTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursadaAlumTabla.setColumnSelectionAllowed(true);
        cursadaAlumTabla.getTableHeader().setReorderingAllowed(false);
        cursadaAlumScroll.setViewportView(cursadaAlumTabla);
        cursadaAlumTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (cursadaAlumTabla.getColumnModel().getColumnCount() > 0) {
            cursadaAlumTabla.getColumnModel().getColumn(0).setResizable(false);
            cursadaAlumTabla.getColumnModel().getColumn(0).setHeaderValue("Legajo");
            cursadaAlumTabla.getColumnModel().getColumn(1).setResizable(false);
            cursadaAlumTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        cursadaAlumAgregarBoton.setText("Agregar...");
        cursadaAlumAgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaAlumAgregarBotonActionPerformed(evt);
            }
        });

        cursadaAlumQuitarBoton.setText("Quitar");
        cursadaAlumQuitarBoton.setEnabled(false);
        cursadaAlumQuitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaAlumQuitarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cursadaAlumBotonesPanelLayout = new javax.swing.GroupLayout(cursadaAlumBotonesPanel);
        cursadaAlumBotonesPanel.setLayout(cursadaAlumBotonesPanelLayout);
        cursadaAlumBotonesPanelLayout.setHorizontalGroup(
            cursadaAlumBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursadaAlumBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursadaAlumAgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaAlumQuitarBoton)
                .addGap(0, 0, 0))
        );
        cursadaAlumBotonesPanelLayout.setVerticalGroup(
            cursadaAlumBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursadaAlumBotonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cursadaAlumBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaAlumAgregarBoton)
                    .addComponent(cursadaAlumQuitarBoton)))
        );

        cursadaProfAgregarBoton.setText("Agregar...");
        cursadaProfAgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaProfAgregarBotonActionPerformed(evt);
            }
        });

        cursadaProfQuitarBoton.setText("Quitar");
        cursadaProfQuitarBoton.setEnabled(false);
        cursadaProfQuitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursadaProfQuitarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cursadaProfBotonesPanelLayout = new javax.swing.GroupLayout(cursadaProfBotonesPanel);
        cursadaProfBotonesPanel.setLayout(cursadaProfBotonesPanelLayout);
        cursadaProfBotonesPanelLayout.setHorizontalGroup(
            cursadaProfBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursadaProfBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursadaProfAgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaProfQuitarBoton)
                .addGap(0, 0, 0))
        );
        cursadaProfBotonesPanelLayout.setVerticalGroup(
            cursadaProfBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursadaProfBotonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cursadaProfBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaProfAgregarBoton)
                    .addComponent(cursadaProfQuitarBoton)))
        );

        cursadaProfTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursadaProfTabla.getTableHeader().setReorderingAllowed(false);
        cursadaProfScroll.setViewportView(cursadaProfTabla);
        cursadaProfTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (cursadaProfTabla.getColumnModel().getColumnCount() > 0) {
            cursadaProfTabla.getColumnModel().getColumn(0).setResizable(false);
            cursadaProfTabla.getColumnModel().getColumn(0).setHeaderValue("Legajo");
            cursadaProfTabla.getColumnModel().getColumn(1).setResizable(false);
            cursadaProfTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        cursadaProfLabel.setText("Profesores");

        try {
            cursadaIdText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("'C'U'R####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout cursadaDatosPanelLayout = new javax.swing.GroupLayout(cursadaDatosPanel);
        cursadaDatosPanel.setLayout(cursadaDatosPanelLayout);
        cursadaDatosPanelLayout.setHorizontalGroup(
            cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursadaDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cursadaProfBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cursadaAlumScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cursadaDatosPanelLayout.createSequentialGroup()
                        .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cursadaPeriodoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cursadaNombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cursadaIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cursadaDatosPanelLayout.createSequentialGroup()
                                .addComponent(cursadaPeriodoACombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cursadaPeriodoBText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cursadaDiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cursadaHoraInicioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cursadaHoraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cursadaHoraFinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cursadaNombreText)
                            .addComponent(cursadaIdText, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cursadaDatosPanelLayout.createSequentialGroup()
                        .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cursadaAlumLabel)
                            .addComponent(cursadaProfLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cursadaAlumBotonesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cursadaProfScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        cursadaDatosPanelLayout.setVerticalGroup(
            cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadaDatosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaIdLabel)
                    .addComponent(cursadaIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaNombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursadaDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaPeriodoLabel)
                    .addComponent(cursadaPeriodoACombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaPeriodoBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaDiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaHoraInicioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaHoraFinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadaHoraLabel))
                .addGap(18, 18, 18)
                .addComponent(cursadaAlumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaAlumScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaAlumBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaProfLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaProfScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaProfBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        cursadasNuevoBoton.setText("Nuevo");

        cursadasBorrarBoton.setText("Borrar");
        cursadasBorrarBoton.setEnabled(false);

        javax.swing.GroupLayout cursadasBotonesPanelLayout = new javax.swing.GroupLayout(cursadasBotonesPanel);
        cursadasBotonesPanel.setLayout(cursadasBotonesPanelLayout);
        cursadasBotonesPanelLayout.setHorizontalGroup(
            cursadasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadasBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursadasNuevoBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadasBorrarBoton)
                .addGap(0, 0, 0))
        );
        cursadasBotonesPanelLayout.setVerticalGroup(
            cursadasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadasBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(cursadasBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadasNuevoBoton)
                    .addComponent(cursadasBorrarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cursadaEditarBoton.setText("Editar");
        cursadaEditarBoton.setEnabled(false);

        cursadaCancelarBoton.setText("Cancelar");
        cursadaCancelarBoton.setEnabled(false);

        cursadaAceptarBoton.setText("Aceptar");
        cursadaAceptarBoton.setEnabled(false);

        javax.swing.GroupLayout cursadaBotonesPanelLayout = new javax.swing.GroupLayout(cursadaBotonesPanel);
        cursadaBotonesPanel.setLayout(cursadaBotonesPanelLayout);
        cursadaBotonesPanelLayout.setHorizontalGroup(
            cursadaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadaBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursadaEditarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaAceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursadaCancelarBoton)
                .addGap(0, 0, 0))
        );
        cursadaBotonesPanelLayout.setVerticalGroup(
            cursadaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadaBotonesPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(cursadaBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursadaEditarBoton)
                    .addComponent(cursadaCancelarBoton)
                    .addComponent(cursadaAceptarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cursadasFiltro.setToolTipText("Filtrar el listado");

        javax.swing.GroupLayout cursadasTabLayout = new javax.swing.GroupLayout(cursadasTab);
        cursadasTab.setLayout(cursadasTabLayout);
        cursadasTabLayout.setHorizontalGroup(
            cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursadasBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cursadasScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(cursadasFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursadaDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cursadaBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cursadasTabLayout.setVerticalGroup(
            cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursadasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursadaDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cursadasTabLayout.createSequentialGroup()
                        .addComponent(cursadasFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cursadasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursadasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursadaBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursadasBotonesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelTabs.addTab("Cursadas", cursadasTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabs)
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void alumnoAgregarAsigBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoAgregarAsigBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoAgregarAsigBotonActionPerformed

    private void alumnoQuitarAsigBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoQuitarAsigBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoQuitarAsigBotonActionPerformed

    private void profesorAgregarAsigBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorAgregarAsigBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesorAgregarAsigBotonActionPerformed

    private void profesorQuitarAsigBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorQuitarAsigBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesorQuitarAsigBotonActionPerformed

    private void asignaturaCorrAgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignaturaCorrAgregarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asignaturaCorrAgregarBotonActionPerformed

    private void asignaturaCorrQuitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignaturaCorrQuitarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asignaturaCorrQuitarBotonActionPerformed

    private void cursadaProfQuitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaProfQuitarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaProfQuitarBotonActionPerformed

    private void cursadaProfAgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaProfAgregarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaProfAgregarBotonActionPerformed

    private void cursadaAlumQuitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaAlumQuitarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaAlumQuitarBotonActionPerformed

    private void cursadaAlumAgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaAlumAgregarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaAlumAgregarBotonActionPerformed

    private void cursadaHoraFinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaHoraFinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaHoraFinTextActionPerformed

    private void cursadaHoraInicioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaHoraInicioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaHoraInicioTextActionPerformed

    private void cursadaPeriodoAComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursadaPeriodoAComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursadaPeriodoAComboActionPerformed

    private void alumnoLegajoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoLegajoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoLegajoTextActionPerformed

    private void alumnoNombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoNombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoNombreTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Principal().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alumnoAceptarBoton;
    private javax.swing.JButton alumnoAgregarAsigBoton;
    private javax.swing.JPanel alumnoAsigBotonesPanel;
    private javax.swing.JLabel alumnoAsigLabel;
    private javax.swing.JScrollPane alumnoAsigScroll;
    private javax.swing.JTable alumnoAsigTabla;
    private javax.swing.JPanel alumnoBotonesPanel;
    private javax.swing.JButton alumnoCancelarBoton;
    private javax.swing.JPanel alumnoDatosPanel;
    private javax.swing.JLabel alumnoDomicilioLabel;
    private javax.swing.JTextField alumnoDomicilioText;
    private javax.swing.JButton alumnoEditarBoton;
    private javax.swing.JLabel alumnoLegajoLabel;
    private javax.swing.JFormattedTextField alumnoLegajoText;
    private javax.swing.JLabel alumnoMailLabel;
    private javax.swing.JTextField alumnoMailText;
    private javax.swing.JLabel alumnoNombreLabel;
    private javax.swing.JTextField alumnoNombreText;
    private javax.swing.JButton alumnoQuitarAsigBoton;
    private javax.swing.JButton alumnosBorrarBoton;
    private javax.swing.JPanel alumnosBotonesPanel;
    private javax.swing.JTextField alumnosFiltro;
    private javax.swing.JButton alumnosNuevoBoton;
    private javax.swing.JScrollPane alumnosScroll;
    private javax.swing.JPanel alumnosTab;
    private javax.swing.JTable alumnosTabla;
    private javax.swing.JButton asignaturaAceptarBoton;
    private javax.swing.JPanel asignaturaBotonesPanel;
    private javax.swing.JButton asignaturaCancelarBoton;
    private javax.swing.JButton asignaturaCorrAgregarBoton;
    private javax.swing.JPanel asignaturaCorrBotonesPanel;
    private javax.swing.JLabel asignaturaCorrLabel;
    private javax.swing.JButton asignaturaCorrQuitarBoton;
    private javax.swing.JScrollPane asignaturaCorrScroll;
    private javax.swing.JTable asignaturaCorrTabla;
    private javax.swing.JPanel asignaturaDatosPanel;
    private javax.swing.JButton asignaturaEditarBoton;
    private javax.swing.JLabel asignaturaIdLabel;
    private javax.swing.JFormattedTextField asignaturaIdText;
    private javax.swing.JLabel asignaturaNombreLabel;
    private javax.swing.JTextField asignaturaNombreText;
    private javax.swing.JButton asignaturasBorrarBoton;
    private javax.swing.JPanel asignaturasBotonesPanel;
    private javax.swing.JTextField asignaturasFiltro;
    private javax.swing.JButton asignaturasNuevoBoton;
    private javax.swing.JScrollPane asignaturasScroll;
    private javax.swing.JPanel asignaturasTab;
    private javax.swing.JTable asignaturasTabla;
    private javax.swing.JButton cursadaAceptarBoton;
    private javax.swing.JButton cursadaAlumAgregarBoton;
    private javax.swing.JPanel cursadaAlumBotonesPanel;
    private javax.swing.JLabel cursadaAlumLabel;
    private javax.swing.JButton cursadaAlumQuitarBoton;
    private javax.swing.JScrollPane cursadaAlumScroll;
    private javax.swing.JTable cursadaAlumTabla;
    private javax.swing.JPanel cursadaBotonesPanel;
    private javax.swing.JButton cursadaCancelarBoton;
    private javax.swing.JPanel cursadaDatosPanel;
    private javax.swing.JComboBox<String> cursadaDiaCombo;
    private javax.swing.JButton cursadaEditarBoton;
    private javax.swing.JFormattedTextField cursadaHoraFinText;
    private javax.swing.JFormattedTextField cursadaHoraInicioText;
    private javax.swing.JLabel cursadaHoraLabel;
    private javax.swing.JLabel cursadaIdLabel;
    private javax.swing.JFormattedTextField cursadaIdText;
    private javax.swing.JLabel cursadaNombreLabel;
    private javax.swing.JTextField cursadaNombreText;
    private javax.swing.JComboBox<String> cursadaPeriodoACombo;
    private javax.swing.JFormattedTextField cursadaPeriodoBText;
    private javax.swing.JLabel cursadaPeriodoLabel;
    private javax.swing.JButton cursadaProfAgregarBoton;
    private javax.swing.JPanel cursadaProfBotonesPanel;
    private javax.swing.JLabel cursadaProfLabel;
    private javax.swing.JButton cursadaProfQuitarBoton;
    private javax.swing.JScrollPane cursadaProfScroll;
    private javax.swing.JTable cursadaProfTabla;
    private javax.swing.JButton cursadasBorrarBoton;
    private javax.swing.JPanel cursadasBotonesPanel;
    private javax.swing.JTextField cursadasFiltro;
    private javax.swing.JButton cursadasNuevoBoton;
    private javax.swing.JScrollPane cursadasScroll;
    private javax.swing.JPanel cursadasTab;
    private javax.swing.JTable cursadasTabla;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JButton profesorAceptarBoton;
    private javax.swing.JButton profesorAgregarAsigBoton;
    private javax.swing.JPanel profesorAsigBotonesPanel;
    private javax.swing.JLabel profesorAsigLabel;
    private javax.swing.JScrollPane profesorAsigScroll;
    private javax.swing.JTable profesorAsigTabla;
    private javax.swing.JPanel profesorBotonesPanel;
    private javax.swing.JButton profesorCancelarBoton;
    private javax.swing.JPanel profesorDatosPanel;
    private javax.swing.JLabel profesorDomicilioLabel;
    private javax.swing.JTextField profesorDomicilioText;
    private javax.swing.JButton profesorEditarBoton;
    private javax.swing.JLabel profesorLegajoLabel;
    private javax.swing.JFormattedTextField profesorLegajoText;
    private javax.swing.JLabel profesorMailLabel;
    private javax.swing.JTextField profesorMailText;
    private javax.swing.JLabel profesorNombreLabel;
    private javax.swing.JTextField profesorNombreText;
    private javax.swing.JButton profesorQuitarAsigBoton;
    private javax.swing.JButton profesoresBorrarBoton;
    private javax.swing.JPanel profesoresBotonesPanel;
    private javax.swing.JTextField profesoresFiltro;
    private javax.swing.JButton profesoresNuevoBoton;
    private javax.swing.JScrollPane profesoresScroll;
    private javax.swing.JPanel profesoresTab;
    private javax.swing.JTable profesoresTabla;
    // End of variables declaration//GEN-END:variables

}
